name: Release and Publish

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Package vscode extension
        run: npm run package -- -o phocus-vscode.vsix

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: phocus-vscode.vsix
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Publish to Marketplace
        run: npm run publish -- -p ${{ secrets.VSCE_PAT }}
